AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/OpenStructUse:
  Exclude:
    - spec/**/*
